<a href="https://colab.research.google.com/github/soffiyahabass1/ArewaDS-Deep-Learning/blob/main/exercise1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Arewa Data Science Academy
Deep Learning Cohort1.0
Name: Taiwo Abass
Email: soffiyahabass1@gmail.com
Title: Week 1 Solution

In [2]:
import torch

random = torch.rand(size=(7,7))

In [3]:
random

tensor([[0.7970, 0.1975, 0.9963, 0.8216, 0.3084, 0.2950, 0.2279],
        [0.8444, 0.7306, 0.1231, 0.6698, 0.9024, 0.5724, 0.4370],
        [0.1630, 0.2877, 0.1329, 0.5197, 0.3374, 0.5243, 0.0397],
        [0.8566, 0.1718, 0.6446, 0.8262, 0.7875, 0.9724, 0.6827],
        [0.4570, 0.5979, 0.6330, 0.4561, 0.9856, 0.8073, 0.6096],
        [0.6846, 0.0139, 0.8939, 0.7765, 0.2269, 0.2931, 0.4931],
        [0.5119, 0.5661, 0.7177, 0.7954, 0.8823, 0.7052, 0.7737]])

In [4]:
random2 = torch.rand(size=(1,7))
random2

tensor([[0.5937, 0.4289, 0.4180, 0.6430, 0.4694, 0.6900, 0.2704]])

In [5]:
mul = torch.matmul(random, random2.T)

In [6]:
mul

tensor([[1.9125],
        [2.2335],
        [1.1408],
        [2.6082],
        [2.2702],
        [1.7274],
        [2.4681]])

In [7]:
torch.manual_seed=(0)

random = torch.rand(size=(7,7))
random2 = torch.rand(size=(1,7))

mul = torch.matmul(random, random2.T)
mul

tensor([[1.4862],
        [1.1178],
        [1.9946],
        [2.2560],
        [1.6444],
        [2.1633],
        [1.4229]])

In [8]:
torch.manual_seed=(0)
tensor1 = torch.rand(size=(2,3))
tensor2 = torch.rand(size=(3,2))

In [9]:

device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'cpu'

In [10]:
tensor_on_gpu = tensor1.to(device)
tensor_on_gpu = tensor2.to(device)
tensor_on_gpu

tensor([[0.8512, 0.3358],
        [0.8548, 0.0855],
        [0.9744, 0.1277]])

In [11]:
torch.manual_seed=(42)

matrix = torch.mm(tensor1, tensor2)
matrix

tensor([[1.4887, 0.4053],
        [0.6717, 0.1946]])

In [12]:
 max = torch.max(matrix)
 max

tensor(1.4887)

In [13]:
min = torch.min(matrix)
min

tensor(0.1946)

In [14]:
max_index = torch.argmax(matrix)
max_index

tensor(0)

In [15]:
min_index = torch.argmin(matrix)
min_index

tensor(3)

In [16]:
random_tensor = torch.rand(size=(1,1,1,10))
random_tensor

tensor([[[[0.5799, 0.8004, 0.7343, 0.9981, 0.0411, 0.3340, 0.5768, 0.7148,
           0.0752, 0.1374]]]])

In [21]:
random_tensor.shape

torch.Size([1, 1, 1, 10])

In [23]:
new= random_tensor[0,0,0,:]

In [25]:
new.shape

torch.Size([10])

In [29]:
torch.manual_seed=(7)
first = random_tensor[:,0,0,0]


first,first.shape

(tensor([0.5799]), torch.Size([1]))

In [39]:
second = random_tensor[0,0,0,:]
second,second.shape

(tensor([0.5799, 0.8004, 0.7343, 0.9981, 0.0411, 0.3340, 0.5768, 0.7148, 0.0752,
         0.1374]),
 torch.Size([10]))